spring:
  http:
    gzip:
      mimeTypes: application/json
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  contextPath: /v${spring.application.majorVersion}
  port: ${port:2222}
endpoints:
  health:
    sensitive: false
management:
  contextPath: /app-admin
  port: ${port:2222}
  security:
    enabled: false
security:
  basic:
    enabled: false
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@portoject.version@'

mediaServer:
  config:
    supportedModelPath: classpath:/%s/media-server/config/supported-models
    modelOverridePath: classpath:/%s/media-server/config/modelOverride.json
    presets: classpath:/%s/media-server/config/presets    
    matrixPath: classpath:/%s/media-server/matrix/%s

support:
  countries: us,ca